# Generated by Django 5.1.1 on 2024-10-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=25, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('numero_celular', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_prontuario', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_cirurgia', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('Atendido', 'Atendido'), ('Não atendido', 'Não Atendido')], default='Não atendido', max_length=12)),
            ],
        ),
    ]
