# Generated by Django 5.1.1 on 2024-10-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='nome',
            new_name='nome2',
        ),
    ]
