# Generated by Django 5.1.1 on 2024-10-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0002_rename_nome_paciente_nome2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='nome2',
            new_name='nome',
        ),
    ]
