# Generated by Django 5.1.1 on 2024-10-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0003_rename_nome2_paciente_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='tipo_cirurgia',
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Prefiro não informar')], max_length=1, null=True),
        ),
    ]
