# Generated by Django 5.1.1 on 2024-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0004_remove_paciente_tipo_cirurgia_paciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
