# Generated by Django 5.1.1 on 2024-10-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0006_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('crm', models.CharField(blank=True, max_length=15, null=True)),
                ('numero_celular', models.CharField(blank=True, max_length=15, null=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cuida.especialidade')),
            ],
        ),
    ]
