# Generated by Django 5.1.1 on 2024-10-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0008_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.TimeField(max_length=5),
        ),
    ]
