# Generated by Django 5.1.1 on 2024-11-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0010_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='sintomas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tratamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
