# Generated by Django 5.1.1 on 2024-11-09 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0010_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.IntegerField()),
                ('imc', models.DecimalField(blank=True, decimal_places=1, max_digits=4)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometrias', to='app_cuida.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SinaisVitais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pulso', models.IntegerField()),
                ('pressao', models.CharField(default='120/80', max_length=10)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinais_vitais', to='app_cuida.paciente')),
            ],
        ),
    ]
