# Generated by Django 5.1.1 on 2024-11-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0011_consulta_diagnostico_consulta_observacoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='sintomas',
            new_name='receita',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='tratamento',
        ),
    ]
