# Generated by Django 5.1.1 on 2024-11-09 17:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0011_biometria_sinaisvitais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data_registro', models.DateField(default=datetime.date.today)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='app_cuida.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='CondicoesEspeciais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data_registro', models.DateField(default=datetime.date.today)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes_especiais', to='app_cuida.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data_registro', models.DateField(default=datetime.date.today)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_ativos', to='app_cuida.paciente')),
            ],
        ),
    ]
