# Generated by Django 5.1.1 on 2024-11-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0012_rename_sintomas_consulta_receita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='receita',
        ),
        migrations.CreateModel(
            name='HistoricoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamento', models.TextField()),
                ('observacoes', models.TextField()),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='app_cuida.paciente')),
            ],
        ),
    ]
