# Generated by Django 5.1.1 on 2024-09-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
