# Generated by Django 5.1.1 on 2024-09-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0003_paciente_numero_prontuario_paciente_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_cirurgia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
