# Generated by Django 5.1.1 on 2024-09-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0004_alter_paciente_nome_alter_paciente_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
