# Generated by Django 5.1.1 on 2024-09-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0005_alter_paciente_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('AT', 'Atendido'), ('NA', 'Não Atendido')], default='NA', max_length=2),
        ),
    ]
