# Generated by Django 5.1.1 on 2024-09-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cuida', '0006_alter_paciente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('ATENDIDO', 'Atendido'), ('NAO ATENDIDO', 'Não Atendido')], default='NAO ATENDIDO', max_length=12),
        ),
    ]
